// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_middleware from "./routes/account/_middleware.ts";
import * as $account_myshorts from "./routes/account/myshorts.tsx";
import * as $callback from "./routes/callback.ts";
import * as $index from "./routes/index.tsx";
import * as $s_id_ from "./routes/s/[id].tsx";
import * as $signin from "./routes/signin.ts";
import * as $signout from "./routes/signout.ts";
import * as $Short from "./islands/Short.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/_middleware.ts": $account_middleware,
    "./routes/account/myshorts.tsx": $account_myshorts,
    "./routes/callback.ts": $callback,
    "./routes/index.tsx": $index,
    "./routes/s/[id].tsx": $s_id_,
    "./routes/signin.ts": $signin,
    "./routes/signout.ts": $signout,
  },
  islands: {
    "./islands/Short.tsx": $Short,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
